stages:
  - prepare
  - build
  - test

prepare_job:
  tags:
    - cuda
  stage: prepare
  script:
    - cd $HOME
    - if [ ! -d "$HOME/arrayfire/.git" ]; then git clone  https://github.com/arrayfire/arrayfire; else echo 'Using arrayfire from cached directory'; fi
    - mkdir -p arrayfire/build && cd arrayfire
    - git pull
    - git submodule init
    - git submodule update
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DBUILD_CPU=OFF -DBUILD_CUDA=ON -DBUILD_OPENCL=OFF -DBUILD_GRAPHICS=OFF -DBUILD_TEST=OFF -DBUILD_EXAMPLES=OFF  -DCMAKE_INSTALL_PREFIX=${HOME}/local .. 
    - make -j 
    - make install
    # Install arrayfire-python
    - cd $HOME
    - if [ ! -d "$HOME/arrayfire-python/.git" ]; then git clone  https://github.com/arrayfire/arrayfire-python.git; else echo 'Using arrayfire-python from cached directory'; fi
    - cd arrayfire-python
    - git pull
    - python setup.py install  --user
  
build_job:
  tags:
    - cuda
  stage: build
  script:
    - python setup.py install --user

test_job:
  tags: 
    - cuda
  stage: test
  script:
    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${HOME}/local/lib
    - coverage run --source afnumpy -m py.test  -v --color=yes --showlocals --durations=10
    - codecov --token=`cat ${HOME}/afnumpy_codecov.token`
